spring:
    profiles: container
    jpa:
        database: MYSQL
        hibernate:
            ddl-auto: validate

    datasource:
        url: jdbc:mysql://jdbc:mysql:3306/HELLO_DB
        username: root
        password: root
        driver-class-name: com.mysql.jdbc.Driver