FROM alpine/git as clone
ARG url
WORKDIR /app
RUN git clone https://github.com/rodrigomirazo/spring-boot-jenkins-pipeline.git#docker-compose

FROM maven:3.5-jdk-8-alpine as build
ARG project
WORKDIR /app
COPY --from=clone /app/${project} /app
RUN mvn install

FROM openjdk:8-jre-alpine
ARG artifactid
ARG version
ENV artifact ${artifactid}-${version}.jar
WORKDIR /app
COPY --from=build /app/target/${artifact} /app
EXPOSE 8080
CMD ["java -jar ${artifact}"]

FROM openjdk:8-jre-alpine
ARG artifactid
ARG version
ENV artifact ${artifactid}-${version}.jar
WORKDIR /app
COPY --from=build /app/target/${artifact} /app
EXPOSE 8082
ENTRYPOINT ["sh", "-c"]
CMD ["java -jar ${artifact}"]