version: '3'

services:
  mysql:
    image: mysql/mysql-server:5.7
    volumes:
      - ./data:/var/lib/mysql

    ports:
      - 3306:3306

    environment:
      ## Use % to allow remote access to all addresses.
      ## Generally not recommended by some people to allow for root.
      # This allows ip ranges from 192.168.0.49 to 192.168.0.54 to connect to root
      - MYSQL_ROOT_HOST=192.168.0.48/255.255.255.248
      - MYSQL_ROOT_HOST=%
    networks:
      network:
        ipv4_address: 172.20.0.2

networks:
  network: #will be prefixed with 'parent_dir_name_' so for me, it will be 'mysql_network'
    ipam:
      config:
        - subnet: 172.20.0.0/16