version: '3.1'

services:

  db:
    image: mysql
    restart: always
    environment:
      MYSQL_USER: "root"
      MYSQL_ROOT_PASSWORD: "root"
      MYSQL_DATABASE: "HELLO_DATABASE"

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080